In [3]:
import numpy as np
import json  
import pandas as pd
from pandas.io.json import json_normalize

In [4]:
df_us = pd.read_csv('../youtube-new/USvideos.csv')
df_us

FileNotFoundError: [Errno 2] File b'../youtube-new/USvideos.csv' does not exist: b'../youtube-new/USvideos.csv'

In [3]:
df_us['country'] = 'USA'
df_us

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,USA
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",USA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,USA
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,USA
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,USA
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,USA
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,USA
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,USA
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,USA

In [4]:
with open('../youtube-new/US_category_id.json') as df_us_category_id:
    us_category = json.load(df_us_category_id)
dataframe_us_category = json_normalize(us_category['items'])
select_feature_us_category = ['id', 'snippet.title']
df_us_category = dataframe_us_category[select_feature_us_category]
df_us_category = df_us_category.rename(columns={"id":"category_id", "snippet.title":"category_title"})

In [5]:
df_us_category.to_csv('us_category.csv', index=False)

In [6]:
df_us_category = pd.read_csv('us_category.csv')
df_us_category

    category_id         category_title
0             1       Film & Animation
1             2       Autos & Vehicles
2            10                  Music
3            15         Pets & Animals
4            17                 Sports
5            18           Short Movies
6            19        Travel & Events
7            20                 Gaming
8            21          Videoblogging
9            22         People & Blogs
10           23                 Comedy
11           24          Entertainment
12           25        News & Politics
13           26          Howto & Style
14           27              Education
15           28   Science & Technology
16           29  Nonprofits & Activism
17           30                 Movies
18           31        Anime/Animation
19           32       Action/Adventure
20           33               Classics
21           34                 Comedy
22           35            Documentary
23           36                  Drama
24           37                 Family
25           38                Foreign
26           39                 Horror
27           40         Sci-Fi/Fantasy
28           41               Thriller
29           42                 Shorts
30           43                  Shows
31           44               Trailers

In [7]:
data_us = pd.merge(df_us, df_us_category, on='category_id')
data_us

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,category_title
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,USA,People & Blogs
1,0mlNzVSJrT0,17.14.11,Me-O Cats Commercial,Nobrand,22,2017-04-21T06:47:32.000Z,"cute|""cats""|""thai""|""eggs""",98966,2486,184,532,https://i.ytimg.com/vi/0mlNzVSJrT0/default.jpg,False,False,False,Kittens come out of the eggs in a Thai commerc...,USA,People & Blogs
2,STI2fI7sKMo,17.14.11,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,22,2017-11-11T15:00:03.000Z,"shawn johnson|""andrew east""|""shawn east""|""shaw...",321053,4451,1772,895,https://i.ytimg.com/vi/STI2fI7sKMo/default.jpg,False,False,False,Subscribe for weekly videos ▶ http://bit.ly/sj...,USA,People & Blogs
3,KODzih-pYlU,17.14.11,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,Grace Helbig,22,2017-11-11T18:08:04.000Z,"itsgrace|""funny""|""comedy""|""vlog""|""grace""|""helb...",197062,7250,217,456,https://i.ytimg.com/vi/KODzih-pYlU/default.jpg,False,False,False,Molly is an god damn amazing human and she cha...,USA,People & Blogs
4,8mhTWqWlQzU,17.14.11,Wearing Online Dollar Store Makeup For A Week,Safiya Nygaard,22,2017-11-11T01:19:33.000Z,wearing online dollar store makeup for a week|...,2744430,115426,1110,6541,https://i.ytimg.com/vi/8mhTWqWlQzU/default.jpg,False,False,False,I found this online dollar store called ShopMi...,USA,People & Blogs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,V6ElE2xs48c,18.02.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1324482,22413,608,1644,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",USA,Shows
40945,V6ElE2xs48c,18.03.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1332252,22461,610,1648,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",USA,Shows
40946,V6ElE2xs48c,18.04.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1340039,22504,615,1648,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",USA,Shows
40947,V6ElE2xs48c,18.05.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1345086,22542,615,1649,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",USA,Shows
40948,V6ElE2xs48c,18.06.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10T21:01:22.000Z,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1351321,22587,616,1649,https://i.ytimg.com/vi/V6ElE2xs48c/default.jpg,False,False,False,"On an island full of Van Gundys, Stan gets tal...",USA,Shows

In [8]:
df_gb = pd.read_csv('../youtube-new/GBvideos.csv')
df_gb

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

In [9]:
df_gb['country'] = 'Great Britain'
df_gb

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,Great Britain
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...,Great Britain
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,Great Britain
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...,Great Britain
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...,Great Britain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,Great Britain
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,Great Britain
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,Great Britain
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,Great Britain
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,Great Britain

In [10]:
with open('../youtube-new/GB_category_id.json') as df_gb_category_id:
    gb_category = json.load(df_gb_category_id)
dataframe_gb_category = json_normalize(gb_category['items'])
select_feature_gb_category = ['id', 'snippet.title']
df_gb_category = dataframe_gb_category[select_feature_gb_category]
df_gb_category = df_gb_category.rename(columns={"id":"category_id", "snippet.title":"category_title"})

In [11]:
df_gb_category.to_csv('gb_category.csv', index=False)

In [12]:
df_gb_category = pd.read_csv('gb_category.csv')
df_gb_category

    category_id        category_title
0             1      Film & Animation
1             2      Autos & Vehicles
2            10                 Music
3            15        Pets & Animals
4            17                Sports
5            18          Short Movies
6            19       Travel & Events
7            20                Gaming
8            21         Videoblogging
9            22        People & Blogs
10           23                Comedy
11           24         Entertainment
12           25       News & Politics
13           26         Howto & Style
14           27             Education
15           28  Science & Technology
16           30                Movies
17           31       Anime/Animation
18           32      Action/Adventure
19           33              Classics
20           34                Comedy
21           35           Documentary
22           36                 Drama
23           37                Family
24           38               Foreign
25           39                Horror
26           40        Sci-Fi/Fantasy
27           41              Thriller
28           42                Shorts
29           43                 Shows
30           44              Trailers

In [13]:
data_gb = pd.merge(df_gb, df_gb_category, on='category_id')
data_gb

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,category_title
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,Great Britain,Howto & Style
1,MyEqfBkzESU,17.14.11,EXTREME GOLDEN TAN TRANSFORMATION,John Maclean,26,2017-11-10T20:40:44.000Z,"Extreme Tan|""Tanning""|""Tanning Bed""|""How to ge...",300617,8133,2693,2911,https://i.ytimg.com/vi/MyEqfBkzESU/default.jpg,False,False,False,-\n\n\nWebsite - http://www.johnmaclean.co.uk\...,Great Britain,Howto & Style
2,b4vTZx_AtHk,17.14.11,How To Dry a Shirt in 30 Seconds,HowToBasic,26,2017-11-09T18:36:48.000Z,"how to dry a shirt in 30 seconds|""how to dry a...",2063667,98804,11682,11443,https://i.ytimg.com/vi/b4vTZx_AtHk/default.jpg,False,False,False,Today I show you how to completely dry a shirt...,Great Britain,Howto & Style
3,OWvCCu2t6Ts,17.14.11,SO Much To Tell You | 32 Weeks Pregnant | MOTH...,Sprinkleofglitter,26,2017-11-10T16:59:50.000Z,"sprinkleofglitter|""sprinkle of glitter""|""Louis...",238843,10028,248,650,https://i.ytimg.com/vi/OWvCCu2t6Ts/default.jpg,False,False,False,A big chat about everything going on in my pre...,Great Britain,Howto & Style
4,9GqL1DSQDL0,17.14.11,GET READY WITH ME + LILY! (we're so immature bye),makeupbymichaelfinch,26,2017-11-09T22:00:00.000Z,"Lily brown|""michael finch""|""makeupbymichaelfin...",332967,22303,700,1523,https://i.ytimg.com/vi/9GqL1DSQDL0/default.jpg,False,False,False,Hey babes! Happy Friday! It's the WEEKENDDD He...,Great Britain,Howto & Style
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38821,JtIY1Naxg0M,18.10.06,Game of Zones - S5E7: NBA 1K,Bleacher Report,43,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1664981,44245,357,4292,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,False,False,NBA rookies are roasting each other over a gam...,Great Britain,Shows
38822,JtIY1Naxg0M,18.11.06,Game of Zones - S5E7: NBA 1K,Bleacher Report,43,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1673959,44316,357,4311,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,False,False,NBA rookies are roasting each other over a gam...,Great Britain,Shows
38823,JtIY1Naxg0M,18.12.06,Game of Zones - S5E7: NBA 1K,Bleacher Report,43,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1686873,44434,360,4318,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,False,False,NBA rookies are roasting each other over a gam...,Great Britain,Shows
38824,JtIY1Naxg0M,18.13.06,Game of Zones - S5E7: NBA 1K,Bleacher Report,43,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1699351,44506,361,4323,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,False,False,NBA rookies are roasting each other over a gam...,Great Britain,Shows
38825,JtIY1Naxg0M,18.14.06,Game of Zones - S5E7: NBA 1K,Bleacher Report,43,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1709880,44588,360,4335,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,False,False,NBA rookies are roasting each other over a gam...,Great Britain,Shows

In [34]:
df = pd.concat([data_us, data_gb])
sort_columns = ['video_id', 'channel_title', 'title', 'category_id', 'category_title', 'tags', 'description', 'views', 'likes', 'dislikes', 'thumbnail_link', 'country']
data_youtube = df[sort_columns]

# Start From Here

In [35]:
data_youtube.head()

,video_id,channel_title,title,category_id,category_title,tags,description,views,likes,dislikes,thumbnail_link,country
0,2kyS6SvSYSE,CaseyNeistat,WE WANT TO TALK ABOUT OUR MARRIAGE,22,People & Blogs,SHANtell martin,SHANTELL'S CHANNEL - https://www.youtube.com/s...,748374,57527,2966,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,USA
1,0mlNzVSJrT0,Nobrand,Me-O Cats Commercial,22,People & Blogs,"cute|""cats""|""thai""|""eggs""",Kittens come out of the eggs in a Thai commerc...,98966,2486,184,https://i.ytimg.com/vi/0mlNzVSJrT0/default.jpg,USA
2,STI2fI7sKMo,Shawn Johnson East,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",22,People & Blogs,"shawn johnson|""andrew east""|""shawn east""|""shaw...",Subscribe for weekly videos ▶ http://bit.ly/sj...,321053,4451,1772,https://i.ytimg.com/vi/STI2fI7sKMo/default.jpg,USA
3,KODzih-pYlU,Grace Helbig,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,22,People & Blogs,"itsgrace|""funny""|""comedy""|""vlog""|""grace""|""helb...",Molly is an god damn amazing human and she cha...,197062,7250,217,https://i.ytimg.com/vi/KODzih-pYlU/default.jpg,USA
4,8mhTWqWlQzU,Safiya Nygaard,Wearing Online Dollar Store Makeup For A Week,22,People & Blogs,wearing online dollar store makeup for a week|...,I found this online dollar store called ShopMi...,2744430,115426,1110,https://i.ytimg.com/vi/8mhTWqWlQzU/default.jpg,USA

# Data Cleaning and Pre-processing

Tags

In [36]:
data_youtube

,video_id,channel_title,title,category_id,category_title,tags,description,views,likes,dislikes,thumbnail_link,country
0,2kyS6SvSYSE,CaseyNeistat,WE WANT TO TALK ABOUT OUR MARRIAGE,22,People & Blogs,SHANtell martin,SHANTELL'S CHANNEL - https://www.youtube.com/s...,748374,57527,2966,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,USA
1,0mlNzVSJrT0,Nobrand,Me-O Cats Commercial,22,People & Blogs,"cute|""cats""|""thai""|""eggs""",Kittens come out of the eggs in a Thai commerc...,98966,2486,184,https://i.ytimg.com/vi/0mlNzVSJrT0/default.jpg,USA
2,STI2fI7sKMo,Shawn Johnson East,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",22,People & Blogs,"shawn johnson|""andrew east""|""shawn east""|""shaw...",Subscribe for weekly videos ▶ http://bit.ly/sj...,321053,4451,1772,https://i.ytimg.com/vi/STI2fI7sKMo/default.jpg,USA
3,KODzih-pYlU,Grace Helbig,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,22,People & Blogs,"itsgrace|""funny""|""comedy""|""vlog""|""grace""|""helb...",Molly is an god damn amazing human and she cha...,197062,7250,217,https://i.ytimg.com/vi/KODzih-pYlU/default.jpg,USA
4,8mhTWqWlQzU,Safiya Nygaard,Wearing Online Dollar Store Makeup For A Week,22,People & Blogs,wearing online dollar store makeup for a week|...,I found this online dollar store called ShopMi...,2744430,115426,1110,https://i.ytimg.com/vi/8mhTWqWlQzU/default.jpg,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
38821,JtIY1Naxg0M,Bleacher Report,Game of Zones - S5E7: NBA 1K,43,Shows,"bleacher report|""br""|""nba""|""philadelphia 76ers...",NBA rookies are roasting each other over a gam...,1664981,44245,357,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,Great Britain
38822,JtIY1Naxg0M,Bleacher Report,Game of Zones - S5E7: NBA 1K,43,Shows,"bleacher report|""br""|""nba""|""philadelphia 76ers...",NBA rookies are roasting each other over a gam...,1673959,44316,357,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,Great Britain
38823,JtIY1Naxg0M,Bleacher Report,Game of Zones - S5E7: NBA 1K,43,Shows,"bleacher report|""br""|""nba""|""philadelphia 76ers...",NBA rookies are roasting each other over a gam...,1686873,44434,360,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,Great Britain
38824,JtIY1Naxg0M,Bleacher Report,Game of Zones - S5E7: NBA 1K,43,Shows,"bleacher report|""br""|""nba""|""philadelphia 76ers...",NBA rookies are roasting each other over a gam...,1699351,44506,361,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,Great Britain
38825,JtIY1Naxg0M,Bleacher Report,Game of Zones - S5E7: NBA 1K,43,Shows,"bleacher report|""br""|""nba""|""philadelphia 76ers...",NBA rookies are roasting each other over a gam...,1709880,44588,360,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,Great Britain